### ISSUE TITLE
Search page alpha

### ISSUE THREAD

**Issue by PeteMontgomery** [jncc/datahub#73]
- [x] Basic styling
- [x] Fragments don't look very good - too short and not clear they are fragments (perhaps add `...`)
- [ ] No results looks bad - we need a results count!
- [ ] Empty search `search?q=` returns all results
- [ ] Ensure that insert-dummy-data creates documents similar to those created with the AWS handler 
- [ ] Resources should link to parent assets in Search results (Use the parent_id and the parent_title fields to make it clear that the resource as it appears in the search results is part of an Asset.)

**Comment by LynnHeeley** [comment]
parent search page in new ticket

**Comment by CathyJinJNCC** [comment]
Done
